#!/bin/bash
shopt -s extglob

CACHE_FILE_PREFIX="/tmp/.cpuhogs"
EPOCH=$(date +%s)
EPOCH_CACHE_FILE="$CACHE_FILE_PREFIX.$EPOCH"

if [[ -f "$EPOCH_CACHE_FILE" ]]; then
    cpuhogs=$(cat "$EPOCH_CACHE_FILE")
    printf "%s" "$cpuhogs"
    exit
fi

# remove old epoch cache files if any
rm -f "$CACHE_FILE_PREFIX".!("$EPOCH")

sorted_cpu=$(ps -u"$(whoami)" -o 'comm,pcpu' --sort=-pcpu | head -n51 | tail -n50)
uniq_cpu=$(echo "$sorted_cpu" | awk '{a[$1]+=$2} END {for(i in a){print i, a[i]}}' | sort -nrk2)
cpuhogs=$(echo "$uniq_cpu" | sed -e '/ 0\.0$/d' -e 's/\s\+\([0-9]\)/:\1/')
echo -n "$cpuhogs" > "$EPOCH_CACHE_FILE"
echo -n "$cpuhogs"

