#!/bin/bash
shopt -s extglob

CACHE_FILE_PREFIX="/tmp/.vmhogs"
EPOCH=$(date +%s)
EPOCH_CACHE_FILE="$CACHE_FILE_PREFIX.$EPOCH"

if [[ -f "$EPOCH_CACHE_FILE" ]]; then
    vmhogs=$(cat "$EPOCH_CACHE_FILE")
    printf "%s" "$vmhogs"
    exit
fi

# remove old epoch cache files if any
rm -f "$CACHE_FILE_PREFIX".!("$EPOCH")

sorted_vsz=$(ps -u"$(whoami)" -o 'comm,vsz' --sort=-vsz | head -n51 | tail -n50)
uniq_vsz=$(echo "$sorted_vsz" | awk '{a[$1]+=$2} END {for(i in a){print i, a[i]}}' | sort -nrk2)
vmhogs=$(echo "$uniq_vsz" | awk '{printf "%s:%.1f\n", $1, $2 / 1024 / 1024}')
echo -n "$vmhogs" > "$EPOCH_CACHE_FILE"
echo -n "$vmhogs"

