[buildPlans.iosevka-hyperlegible] # <iosevka-custom> is your plan name
# v7.0.3
family = 'Iosevka Hyperlegible'   # Font menu family name
spacing = 'fixed'                  # Optional; Values: 'normal', 'term', 'fontconfig-mono', or 'fixed'
serifs = 'sans'                   # Optional; Values: 'sans' or 'slab'
no-cv-ss = true
###################################################################################################
# Configure variants
# Optional; Whether to inherit a 'ss##' variant
[buildPlans.iosevka-hyperlegible.variants]
# inherits = 'ss01'              # use defaults instead (of inheriting)
# Optional; Configure single character's variant
[buildPlans.iosevka-hyperlegible.variants.design]
capital-a = 'straight-serifless'
capital-b = 'standard-serifless'
capital-c = 'serifless'
capital-d = 'more-rounded-serifless'  # D
capital-e = 'serifless'
capital-f = 'serifless'
capital-g = 'toothed-serifless-hooked'# G
capital-h = 'serifless'
capital-i = 'short-serifed'              # I
capital-j = 'serifless'               # J
capital-k = 'straight-serifless'              # K
capital-l = 'serifless'               # J
capital-m = 'slanted-sides-hanging'             # M
capital-n = 'standard'
capital-p = 'closed'
capital-q = 'crossing'              # Q
capital-u = 'toothless-rounded'
capital-w = 'straight'       # W
a = 'double-storey-serifless'
b = 'toothed'
c = 'serifless'
d = 'toothed-serifless'
e = 'flat-crossbar'
f = 'flat-hook-crossbar-at-x-height'
g = 'single-storey-serifless'
h = 'straight'
i = 'hooky'
j = 'flat-hook-serifless'
k = 'straight-serifless'
l = 'flat-tailed'
m = 'short-leg'
n = 'straight'
p = 'eared'
q = 'tailed'
r = 'compact'
s = 'serifless'
t = 'flat-hook-short-neck2'
u = 'toothed'
v = 'straight'
w = 'straight'
x = 'straight-serifless'
y = 'straight-turn'
z = 'straight-serifless'
zero = 'long-dotted'                        # 0
one = 'base'                          # 1
two = 'straight-neck'                 # 2
three = 'twoarcs'
four = 'closed'                       # 4
five = 'oblique-upper-left-bar'       # 5
six = 'open-contour'                          # 6
seven = 'bend-serifless'
eight = 'two-circles'                 # 8
nine = 'straight-bar'
tilde = 'low'
asterisk = 'hex-low'
underscore = 'high'
paragraph-sign = 'low'
caret = 'high'
paren = 'normal'
brace = 'curly'
number-sign = 'upright'
ampersand = 'closed'
at = 'threefold'
dollar = 'through-cap'
cent = 'through'
percent = 'rings-continuous-slash'
bar = 'force-upright'
ascii-single-quote = 'straight'
ascii-grave = 'straight'
question = 'corner-flat-hooked'
cyrl-ka = 'symmetric-touching-serifless'        # к
lower-iota = 'flat-tailed'            # ι
lower-lambda = 'straight-turn'        # λ
# Optional; Configure single character's variant for Upright and Oblique; Overrides [design]
[buildPlans.iosevka-hyperlegible.variants.upright]
# Optional; Configure single character's variant for Italic only; Overrides [design]
[buildPlans.iosevka-hyperlegible.variants.italic]
a = 'double-storey-serifless'
d = 'toothed-serifless'
e = 'flat-crossbar'
f = 'flat-hook-crossbar-at-x-height'
k = 'straight-serifless'
u = 'toothed'
y = 'straight-turn'
eszet = 'sulzbacher'                  # ß
# End variant section
###################################################################################################
###################################################################################################
# Configure ligations
[buildPlans.iosevka-hyperlegible.ligations]
inherits = 'default-calt'   # Optional; inherits an existing ligation set
disables = []               # Optional; disable specific ligation groups, overrides inherited ligation set
enables  = []               # Optional; enable specific ligation groups, overrides inherited ligation set
# End ligation section
###################################################################################################
###################################################################################################
# Override default building weights
# When buildPlans.<plan name>.weights is absent, all weights would built and mapped to
# default values.
# IMPORTANT : Currently 'menu' and 'css' property only support numbers between 0 and 1000.
#             and 'shape' properly only supports number between 100 and 900 (inclusive).
#             If you decide to use custom weights you have to define all the weights you
#             plan to use otherwise they will not be built.
[buildPlans.iosevka-hyperlegible.weights.regular]
shape = 400  # Weight for glyph shapes.
menu  = 400  # Weight for the font's names.
css   = 400  # Weight for webfont CSS.
[buildPlans.iosevka-hyperlegible.weights.book]
shape = 450
menu  = 450  # Use 450 here to name the font's weight 'Book'
css   = 450
[buildPlans.iosevka-hyperlegible.weights.bold]
shape = 700
menu  = 700
css   = 700
# End weight section
###################################################################################################
###################################################################################################
# Override default building slope sets
# Format: <upright|italic|oblique> = <'normal'|'italic'|'oblique'>
# When this section is absent, all slopes would be built.
[buildPlans.iosevka-hyperlegible.slopes]
upright = 'normal'
italic = 'italic'
oblique = 'oblique'
# End slope section
###################################################################################################
###################################################################################################
# Override default building widths
# When buildPlans.<plan name>.widths is absent, all widths would built and mapped to
# default values.
# IMPORTANT : Currently 'shape' property only supports numbers between 434 and 664 (inclusive),
#             while 'menu' only supports integers between 1 and 9 (inclusive).
#             The 'shape' parameter specifies the unit width, measured in 1/1000 em. The glyphs'
#             width are equal to, or a simple multiple of the unit width.
#             If you decide to use custom widths you have to define all the widths you plan to use,
#             otherwise they will not be built.
[buildPlans.iosevka-hyperlegible.widths.normal]
shape = 500     # Unit Width, measured in 1/1000 em.
menu  = 5          # Width grade for the font's names.
css   = 'normal'   # 'font-stretch' property of webfont CSS.
[buildPlans.iosevka-hyperlegible.widths.extended]
shape = 576
menu  = 7
css   = 'expanded'
# End width section
###################################################################################################
###################################################################################################
# Character Exclusion
# Specify character ranges in the section below to exclude certain characters from the font being
# built. Remove this section when this feature is not needed.
[buildPlans.iosevka-hyperlegible.exclude-chars]
ranges = [[10003, 10008]]
# End character exclusion
###################################################################################################
###################################################################################################
# Compatibility Ligatures
# Certain applications like Emacs does not support proper programming liagtures provided by
# OpenType, but can support ligatures provided by PUA codepoints. Therefore you can edit the
# following section to build PUA characters that are generated from the OpenType ligatures.
# Remove this section when compatibility ligatures are not needed.
[[buildPlans.iosevka-hyperlegible.compatibility-ligatures]]
unicode = 57600 # 0xE100
featureTag = 'calt'
sequence = '<*>'
# End compatibility ligatures section
###################################################################################################
###################################################################################################
# Metric overrides
# Certain metrics like line height (leading) could be overridden in your build plan file.
# Edit the values to change the metrics. Remove this section when overriding is not needed.
[buildPlans.iosevka-hyperlegible.metric-override]
winMetricAscenderPad = 0
winMetricDescenderPad = 0
powerlineScaleY = 1
powerlineScaleX = 1
powerlineShiftY = 0
powerlineShiftX = 0

# sb = 60
# cap = 785
# xheight = 565
# symbolMid = 395
[buildPlans.iosevka-hyperlegible.metric-override.multiplies]
leading = 1.0000
[buildPlans.iosevka-hyperlegible.metric-override.adds]
# End metric override section
###################################################################################################
